services:
  db:
    image: postgres:16-alpine
    container_name: postgres-kira-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: studio
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data_dev:
