name: kira-sekira-main

services:
  postgres:
    container_name: kira-postgres-main
    image: postgres:16-alpine
    env_file: .env.main
    volumes:
      - postgres_data_main:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - internal

  main:
    build:
      context: .
      dockerfile: apps/main/Dockerfile
    env_file: .env.main
    restart: unless-stopped
    networks:
      - internal
    depends_on:
      - postgres

  models:
    build:
      context: .
      dockerfile: apps/models/Dockerfile
    env_file: .env.main
    restart: unless-stopped
    networks:
      - internal
    depends_on:
      - postgres

  studio:
    build:
      context: .
      dockerfile: apps/studio/Dockerfile
    env_file: .env.main
    restart: unless-stopped
    networks:
      - internal
    depends_on:
      - postgres
    volumes:
      - studio_media_main:/app/media

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data_main:/data
    restart: unless-stopped
    networks:
      - internal

volumes:
  postgres_data_main:
  studio_media_main:
  caddy_data_main:

networks:
  internal:
