FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build:main -- --configuration production

FROM node:22-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev
COPY --from=build /app/dist/main ./dist/main
ENV PORT=4000
EXPOSE 4000
CMD ["node", "dist/main/server/server.mjs"]
